version: 0.0
os: linux

files:
  - source: /
    destination: /data/yroun/server/janggi-server
    overwrite: yes

permissions:

  - object: /data/yroun/server/janggi-server
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

  - object: /data/yroun/nginx
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user
